/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppGenresGenreRouteImport } from './routes/_app/genres/$genre'
import { Route as AppAnimeAddRouteImport } from './routes/_app/anime/add'
import { Route as AppAnimeAnimeIdRouteImport } from './routes/_app/anime/$animeId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGenresGenreRoute = AppGenresGenreRouteImport.update({
  id: '/genres/$genre',
  path: '/genres/$genre',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAnimeAddRoute = AppAnimeAddRouteImport.update({
  id: '/anime/add',
  path: '/anime/add',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAnimeAnimeIdRoute = AppAnimeAnimeIdRouteImport.update({
  id: '/anime/$animeId',
  path: '/anime/$animeId',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/anime/$animeId': typeof AppAnimeAnimeIdRoute
  '/anime/add': typeof AppAnimeAddRoute
  '/genres/$genre': typeof AppGenresGenreRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AppIndexRoute
  '/anime/$animeId': typeof AppAnimeAnimeIdRoute
  '/anime/add': typeof AppAnimeAddRoute
  '/genres/$genre': typeof AppGenresGenreRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/anime/$animeId': typeof AppAnimeAnimeIdRoute
  '/_app/anime/add': typeof AppAnimeAddRoute
  '/_app/genres/$genre': typeof AppGenresGenreRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/anime/$animeId'
    | '/anime/add'
    | '/genres/$genre'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/' | '/anime/$animeId' | '/anime/add' | '/genres/$genre'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/'
    | '/_app/anime/$animeId'
    | '/_app/anime/add'
    | '/_app/genres/$genre'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/genres/$genre': {
      id: '/_app/genres/$genre'
      path: '/genres/$genre'
      fullPath: '/genres/$genre'
      preLoaderRoute: typeof AppGenresGenreRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/anime/add': {
      id: '/_app/anime/add'
      path: '/anime/add'
      fullPath: '/anime/add'
      preLoaderRoute: typeof AppAnimeAddRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/anime/$animeId': {
      id: '/_app/anime/$animeId'
      path: '/anime/$animeId'
      fullPath: '/anime/$animeId'
      preLoaderRoute: typeof AppAnimeAnimeIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppAnimeAnimeIdRoute: typeof AppAnimeAnimeIdRoute
  AppAnimeAddRoute: typeof AppAnimeAddRoute
  AppGenresGenreRoute: typeof AppGenresGenreRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppAnimeAnimeIdRoute: AppAnimeAnimeIdRoute,
  AppAnimeAddRoute: AppAnimeAddRoute,
  AppGenresGenreRoute: AppGenresGenreRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
